COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:minimal-json',
    '//protocols/p4runtime/model:onos-protocols-p4runtime-model',
    '//drivers/default:onos-drivers-default',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

BUNDLES = [
    '//apps/p4-tutorial/basic:onos-apps-p4-tutorial-basic',
]

onos_app (
    app_name = 'org.onosproject.p4tutorial.basic',
    title = 'P4 Tutorial Basic',
    category = 'Pipeconf',
    url = 'http://onosproject.org',
    description = 'Provides pipeconf for the ONOS-P4 Tutorial',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.drivers.p4runtime',
    ]
)
